### PR TITLE
Server Messages

### PR DESCRIPTION
**Pull request by andrew-brainerd**
Updates to support processing user input messages on the server

### CODE REVIEW

**Review by cheiney — APPROVED** [review]
I'm going to approve this as if I know what I'm doing :) ⚡️

**Comment by andrew-brainerd** [comment]
@cheiney Cool. We usually wait for the person that submitted the PR to do the merge though.

**Comment by cheiney** [comment]
Oops I was too excited!

**Comment by andrew-brainerd** [comment]
@cheiney No worries man. It's not a requirement to have to merge your own PRs.

**Pull request merged**
